[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pyOrcaSDK"
version = "0.0.1"
readme = "README.md"
description = "pyOrcaSDK ported from the C++ orcaSDK library"
authors = [
    {name = "Jake Taranov", email = "jtaranov@irisdynamics.com"},
]
requires-python = ">=3.8"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
cmake.build-type = "Debug"
cmake.version = "CMakeLists.txt"
sdist.include = ["pyOrcaSDK/*.pyi"]
sdist.exclude = ["cleanup.py", "tests/"]
cmake.args = [
    "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${CMAKE_CURRENT_BINARY_DIR}/pyOrcaSDK",
    "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_CURRENT_BINARY_DIR}/pyOrcaSDK",
    "-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=${CMAKE_CURRENT_BINARY_DIR}/pyOrcaSDK"
]


[tool.cibuildwheel]
build = "cp312-*"
build-verbosity = 2

# Windows-specific settings
[tool.cibuildwheel.windows]
archs = ["x86", "AMD64", "ARM64"]

# Linux-specific settings
[tool.cibuildwheel.linux]
archs = ["x86_64", "i686", "aarch64"]

# macOS-specific settings
[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
